version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - gochecknoglobals
  settings:
    depguard:
      rules:
        main:
          files:
            - "cmd/**/*.go"
            - "main.go"
          allow:
            - "fmt"
            - "os"
            - "context"
            - "strings"
            - "github.com/spf13/cobra"
            - "hardcover-cli/internal/client"
            - "hardcover-cli/internal/config"
        test:
          files:
            - "**/*_test.go"
          allow:
            - "fmt"
            - "os"
            - "context"
            - "strings"
            - "bytes"
            - "net/http"
            - "net/http/httptest"
            - "path/filepath"
            - "encoding/json"
            - "testing"
            - "time"
            - "github.com/spf13/cobra"
            - "github.com/stretchr/testify/assert"
            - "github.com/stretchr/testify/require"
            - "hardcover-cli/internal/client"
            - "hardcover-cli/internal/config"
            - "hardcover-cli/cmd"
        internal:
          files:
            - "internal/**/*.go"
          allow:
            - "fmt"
            - "os"
            - "path/filepath"
            - "gopkg.in/yaml.v3"
            - "bytes"
            - "context"
            - "encoding/json"
            - "io"
            - "net/http"
            - "time"
            - "github.com/stretchr/testify/assert"
            - "github.com/stretchr/testify/require"
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - wrapperFunc
        - dupImport
        - ifElseChain
      enabled-tags:
        - performance
        - style
        - experimental
        - diagnostic
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
    lll:
      line-length: 120
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      confidence: 0.8
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - staticcheck
        text: 'SA1019:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - hardcover-cli
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
