name: 'Setup Go Environment'
description: 'Setup Go environment with caching and dependency download'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.23'
  cache-key:
    description: 'Cache key for Go modules'
    required: false
    default: '${{ runner.os }}-go-${{ inputs.go-version }}-${{ hashFiles(''**/go.sum'') }}'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-go-${{ inputs.go-version }}-
          ${{ runner.os }}-go-

    - name: Download dependencies
      shell: bash
      run: go mod download 